---
apiVersion: v2
name: cilium
home: https://cilium.io/
version: 1.14.0-dev0
appVersion: 1.14.0-dev0
icon: https://cdn.jsdelivr.net/gh/cilium/cilium@main/Documentation/images/logo-solo.svg
description: eBPF-based Networking, Security, and Observability
